# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
#- task: Mirror Repositories@1
#  inputs:
#    sourceType: true
#    sourceURL: 'https://dev.azure.com/lgarita0971/Demo%20Azure/_git/ci-cd-nodejs'
#    sourcePAT: 'v7auw6otco77fmmgpgniaugvygvnss54synlw3lapluuqztc2xfq'
#    destinationType: true
#    destinationURL: 'https://gitlab.com/RM_GBM/prueba-migracion1/prueba-migracion2/test'
#    destinationPAT: 'glpat-LfbxcxX4ZtPtAFQBfx78'

- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: '$(Build.Repository.Uri)'
    sourceGitRepositoryPersonalAccessToken: 'v7auw6otco77fmmgpgniaugvygvnss54synlw3lapluuqztc2xfq'
    sourceVerifySSLCertificate: false
    destinationGitRepositoryUri: 'https://gitlab.com/RM_GBM/prueba-migracion1/prueba-migracion2/test.git'
    destinationGitRepositoryPersonalAccessToken: 'glpat-LfbxcxX4ZtPtAFQBfx78'
    destinationVerifySSLCertificate: false
