name: Test pipelines

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

# Jobs a ejecutar
jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Usa un checkout action para obtener el código fuente del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Imprimir "Hello World"
      - name: Print Hello World
        run: echo "Hello World"
